app/Models/Deployment.php
<?php

/*
 * This file is part of Fixhub.
 *
 * Copyright (C) 2016 Fixhub.org
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Fixhub\Models;

use Fixhub\Bus\Events\ModelChanged;
use Fixhub\Presenters\RuntimeInterface;
use Fixhub\Presenters\DeploymentPresenter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use McCool\LaravelAutoPresenter\HasPresenter;

/**
 * Deployment model.
 */
class Deployment extends Model implements HasPresenter, RuntimeInterface
{
    use SoftDeletes;

    const COMPLETED             = 0;
    const PENDING               = 1;
    const DEPLOYING             = 2;
    const FAILED                = 3;
    const COMPLETED_WITH_ERRORS = 4;
    const ABORTING              = 5;
    const ABORTED               = 6;
    const APPROVING             = 7;
    const APPROVED              = 8;
    const LOADING               = 'Loading';

    public static $currentDeployment = [];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['reason', 'branch', 'project_id', 'source', 'build_url',
                           'commit', 'committer_email', 'committer', ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['created_at', 'deleted_at', 'updated_at', 'user', 'commands'];

    /**
     * Additional attributes to include in the JSON representation.
     *
     * @var array
     */
    protected $appends = ['project_name', 'deployer_name', 'commit_url',
                          'short_commit', 'branch_url', 'repo_failure', ];

    /**
     * The fields which should be tried as Carbon instances.
     *
     * @var array
     */
    protected $dates = ['started_at', 'finished_at'];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'         => 'integer',
        'project_id' => 'integer',
        'user_id'    => 'integer',
        'status'     => 'integer',
        'is_webhook' => 'boolean',
    ];

    /**
     * Override the boot method to bind model event listeners.
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        static::saved(function (Deployment $model) {
            event(new ModelChanged($model, 'deployment'));
        });
    }

    /**
     * Belongs to relationship.
     *
     * @return Project
     */
    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * Belongs to relationship.
     *
     * @return User
     */
    public function user()
    {
        return $this->belongsTo(User::class)
                    ->withTrashed();
    }

    /**
     * Define a command attribute to be able to access to commands relationship.
     *
     * @return Command
     */
    public function getCommandsAttribute()
    {
        if (!$this->relationLoaded('commands')) {
            $this->loadCommands();
        }

        if ($this->relationLoaded('commands')) {
            return $this->getRelation('commands');
        }

        return collect([]);
    }

    /**
     * Query the DB and load the HasMany relationship for commands.
     *
     * @return Deployment
     */
    private function loadCommands()
    {
        $collection = Command::join('deploy_steps', 'commands.id', '=', 'deploy_steps.command_id')
                             ->where('deploy_steps.deployment_id', $this->getKey())
                             ->distinct()
                             ->orderBy('step')
                             ->orderBy('order')
                             ->get(['commands.*', 'deployment_id']);

        $hasMany = new HasMany(Command::query(), $this, 'deployment_id', 'id');
        $hasMany->matchMany([$this], $collection, 'commands');

        return $this;
    }

    /**
     * Has many relationship.
     *
     * @return DeployStep
     */
    public function steps()
    {
        return $this->hasMany(DeployStep::class);
    }

    /**
     * Determines whether the deployment is running.
     *
     * @return bool
     */
    public function isRunning()
    {
        return ($this->status === self::DEPLOYING);
    }

    /**
     * Determines whether the deployment is pending.
     *
     * @return bool
     */
    public function isPending()
    {
        return ($this->status === self::PENDING);
    }

    /**
     * Determines whether the deployment is successful.
     *
     * @return bool
     */
    public function isSuccessful()
    {
        return ($this->status === self::COMPLETED);
    }

    /**
     * Determines whether the deployment failed.
     *
     * @return bool
     */
    public function isFailed()
    {
        return ($this->status === self::FAILED);
    }

    /**
     * Determines whether the deployment is waiting to be approved.
     *
     * @return bool
     */
    public function isApproving()
    {
        return ($this->status === self::APPROVING);
    }

    /**
     * Determines whether the deployment is approved.
     *
     * @return bool
     */
    public function isApproved()
    {
        return ($this->status === self::APPROVED);
    }

    /**
     * Determines whether the deployment is waiting to be aborted.
     *
     * @return bool
     */
    public function isAborting()
    {
        return ($this->status === self::ABORTING);
    }

    /**
     * Determines whether the deployment is aborted.
     *
     * @return bool
     */
    public function isAborted()
    {
        return ($this->status === self::ABORTED);
    }

    /**
     * Determines if the deployment is the latest deployment.
     *
     * @return bool
     */
    public function isCurrent()
    {
        if (!isset(self::$currentDeployment[$this->project_id])) {
            self::$currentDeployment[$this->project_id] = self::where('project_id', $this->project_id)
                                                              ->where('status', self::COMPLETED)
                                                              ->orderBy('id', 'desc')
                                                              ->first();
        }

        if (isset(self::$currentDeployment[$this->project_id])) {
            return (self::$currentDeployment[$this->project_id]->id === $this->id);
        }

        return false;
    }

    /**
     * Determines how long the deploy took.
     *
     * @return false|int False if the deploy is still running, otherwise the runtime in seconds
     */
    public function runtime()
    {
        if (!$this->finished_at) {
            return;
        }

        return $this->started_at->diffInSeconds($this->finished_at);
    }

    /**
     * Gets the HTTP URL to the commit.
     *
     * @return string|false
     */
    public function getCommitUrlAttribute()
    {
        if ($this->commit !== self::LOADING) {
            $info = $this->project->accessDetails();
            if (isset($info['domain']) && isset($info['reference'])) {
                $path = 'commit';
                if (preg_match('/bitbucket/', $info['domain'])) {
                    $path = 'commits';
                }

                return 'http://' . $info['domain'] . '/' . $info['reference'] . '/' . $path . '/' . $this->commit;
            }
        }

        return false;
    }

    /**
     * Gets the short commit hash.
     *
     * @return string
     */
    public function getShortCommitAttribute()
    {
        if ($this->commit !== self::LOADING) {
            return substr($this->commit, 0, 7);
        }

        return $this->commit;
    }

    /**
     * Gets the HTTP URL to the branch.
     *
     * @return string|false
     * @see \Fixhub\Models\Project::accessDetails()
     */
    public function getBranchURLAttribute()
    {
        return $this->project->getBranchUrlAttribute($this->branch);
    }

    /**
     * Generates a slack payload for the deployment.
     *
     * @return array
     */
    public function notifySlackPayload()
    {
        $color  = 'good';
        $message = trans('notifySlacks.success_message');

        if ($this->status === self::FAILED) {
            $color  = 'danger';
            $message = trans('notifySlacks.failed_message');
        }

        $payload = [
            'attachments' => [
                [
                    'fallback' => sprintf($message, '#' . $this->id),
                    'text'     => sprintf($message, sprintf(
                        '<%s|#%u>',
                        route('deployments', ['id' => $this->id]),
                        $this->id
                    )),
                    'color'    => $color,
                    'fields'   => [
                        [
                            'title' => trans('notifySlacks.project'),
                            'value' => sprintf(
                                '<%s|%s>',
                                route('projects', ['id' => $this->project_id]),
                                $this->project->name
                            ),
                            'short' => true,
                        ], [
                            'title' => trans('notifySlacks.commit'),
                            'value' => $this->commit_url ? sprintf(
                                '<%s|%s>',
                                $this->commit_url,
                                $this->short_commit
                            ) : $this->short_commit,
                            'short' => true,
                        ], [
                            'title' => trans('notifySlacks.committer'),
                            'value' => $this->committer,
                            'short' => true,
                        ], [

app/Models/User.php
<?php

/*
 * This file is part of Fixhub.
 *
 * Copyright (C) 2016 Fixhub.org
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Fixhub\Models;

use Fixhub\Models\Traits\BroadcastChanges;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Support\Facades\Hash;
use Creativeorange\Gravatar\Facades\Gravatar;

/**
 * User model.
 */
class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, CanResetPassword, Authorizable, SoftDeletes, BroadcastChanges;

    /**
     * The admin level of user.
     *
     * @var int
     */
    const LEVEL_ADMIN = 1;

    /**
     * The general level of user.
     *
     * @var int
     */
    const LEVEL_USER = 2;

    /**
     * The operator level of user.
     *
     * @var int
     */
    const LEVEL_OPERATOR = 3;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password', 'nickname', 'level', 'avatar', 'skin', 'language'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['deleted_at', 'updated_at', 'password', 'remember_token', 'google2fa_secret'];

    /**
     * Additional attributes to include in the JSON representation.
     *
     * @var array
     */
    protected $appends = ['has_two_factor_authentication', 'role_name'];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
    ];

    /**
    * Has any password being inserted by default.
    *
    * @param string $password
    *
    * @return \Fixhub\Models\User
    */
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);

        return $this;
    }

    /**
     * Generate a change email token.
     *
     * @return string
     */
    public function requestEmailToken()
    {
        $this->email_token = str_random(40);
        $this->save();

        return $this->email_token;
    }

    /**
     * Returns the user avatar url.
     *
     * @return string
     */
    public function getAvatarUrlAttribute()
    {
        if ($this->avatar) {
            return url($this->avatar);
        }

        return Gravatar::get($this->email);
    }

    /**
     * Returns whether a user is at user level.
     *
     * @return bool
     */
    public function getIsUserAttribute()
    {
        return $this->level == self::LEVEL_USER;
    }

    /**
     * Returns whether a user is at admin level.
     *
     * @return bool
     */
    public function getIsAdminAttribute()
    {
        return $this->level == self::LEVEL_ADMIN;
    }

    /**
     * Returns whether a user is at operator level.
     *
     * @return bool
     */
    public function getIsOperatorAttribute()
    {
        return $this->level == self::LEVEL_OPERATOR;
    }

    /**
     * Determines whether the user has Google 2FA enabled.
     *
     * @return bool
     * @SuppressWarnings(PHPMD.BooleanGetMethodName)
     */
    public function getHasTwoFactorAuthenticationAttribute()
    {
        return !empty($this->google2fa_secret);
    }

    /**
     * Get the user role.
     *
     * @return string
     */
    public function getRoleNameAttribute()
    {
        if ($this->level == User::LEVEL_ADMIN) {
            return trans('users.level.admin');
        } elseif ($this->level == User::LEVEL_OPERATOR) {
            return trans('users.level.operator');
        } elseif ($this->level == User::LEVEL_USER) {
            return trans('users.level.user');
        }

        return 'Unknown';
    }
}

resources/views/projects/_partials/check_urls.blade.php
<div class="box">
    <div class="box-header">
        <div class="pull-right">
            <button type="button" class="btn btn-success" title="{{ trans('checkUrls.create') }}" data-toggle="modal" data-target="#checkurl"><span class="ion ion-plus"></span> {{ trans('checkUrls.create') }}</button>
        </div>
        <h3 class="box-title">{{ trans('checkUrls.label') }}</h3>
    </div>


    <div class="box-body" id="no_checkurls">
        <p>{{ trans('checkUrls.none') }}</p>
    </div>

    <div class="box-body table-responsive">
        <table class="table table-striped" id="checkurl_list">
            <thead>
                <tr>
                    <th width="10%">{{ trans('checkUrls.title') }}</th>
                    <th width="45%">{{ trans('checkUrls.url') }}</th>
                    <th width="10%">{{ trans('checkUrls.frequency') }}</th>
                    <th width="15%">最近检测</th>
                    <th width="10%">{{ trans('checkUrls.last_status') }}</th>
                    <th width="10%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

@push('templates')
    <script type="text/template" id="checkUrls-template">
        <td><%- title %></td>
        <td><%- url %></td>
        <td><%- interval_label %></td>
        <td><%- updated_at %></td>
        <td>
            <span class="label label-<%- status_css %>">
                <i class="ion ion-<%-icon_css %>"></i>
                <%- status %>
            </span>
        </td>
        <td>
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-default btn-edit" title="{{ trans('checkUrls.edit') }}" data-toggle="modal" data-backdrop="static" data-target="#checkurl"><i class="ion ion-compose"></i></button>
                <button type="button" class="btn btn-danger btn-delete" title="{{ trans('app.delete') }}" data-toggle="modal" data-backdrop="static" data-target="#model-trash"><i class="ion ion-trash-a"></i></button>
            </div>
        </td>
    </script>
@endpush

resources/views/projects/_partials/commands.blade.php
@if (Route::currentRouteName() == 'projects' && $current_user->is_admin)
<div class="callout">
    <h4>{{ trans('commands.deploy_webhook') }} <i class="ion ion-help-buoy" id="show_help" data-toggle="modal" data-backdrop="static" data-target="#help"></i></h4>
    <code id="webhook">{{ $project->webhook_url }}</code><button class="btn btn-xs btn-link" id="new_webhook" title="{{ trans('commands.generate_webhook') }}" data-project-id="{{ $project->id }}"><i class="ion ion-refresh"></i></button>
</div>
@endif

<div class="box">
    <div class="box-header">
        <h3 class="box-title">{{ trans('commands.label') }}</h3>
    </div>
    <div class="box-body table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{{ trans('commands.step') }}</th>
                    <th>{{ trans('commands.before') }}</th>
                    <th>{{ trans('commands.current') }}</th>
                    <th>{{ trans('commands.after') }}</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach(['clone', 'install', 'activate', 'purge'] as $index => $stage)
                <tr>
                    <td>{{ $index+1 }}</td>
                    <td>{{ $project->{'before_'.$stage} }}</td>
                    <td>{{ trans('commands.'.$stage) }}</td>
                    <td>{{ $project->{'after_'.$stage} }}</td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="{{ route($route, ['id' => $project->id, 'command' => $stage]) }}" class="btn btn-default" title="{{ trans('commands.configure') }}"><i class="ion ion-ios-gear"></i></a>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/projects/_partials/config_files.blade.php
<div class="box">
    <div class="box-header">
        <div class="pull-right">
            <button type="button" class="btn btn-success" title="{{ trans('configFiles.create') }}" data-toggle="modal" data-target="#configfile"><span class="ion ion-plus"></span> {{ trans('configFiles.create') }}</button>
        </div>
        <h3 class="box-title">{{ trans('configFiles.label') }}</h3>
    </div>


    <div class="box-body" id="no_configfiles">
        <p>{{ trans('configFiles.none') }}</p>
    </div>

    <div class="box-body table-responsive">
        <table class="table table-striped" id="configfile_list">
            <thead>
                <tr>
                    <th width="30%">{{ trans('configFiles.name') }}</th>
                    <th width="40%">{{ trans('configFiles.path') }}</th>
                    <th width="30%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

@push('templates')
    <script type="text/template" id="config-files-template">
        <td><%- name %></td>
        <td><%- path %></td>
        <td>
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-default btn-view" title="{{ trans('configFiles.view') }}" data-toggle="modal" data-backdrop="static" data-target="#view-configfile"><i class="ion ion-eye"></i></button>
                <button type="button" class="btn btn-default btn-edit" title="{{ trans('configFiles.edit') }}" data-toggle="modal" data-backdrop="static" data-target="#configfile"><i class="ion ion-compose"></i></button>
                <button type="button" class="btn btn-danger btn-delete" title="{{ trans('app.delete') }}" data-toggle="modal" data-backdrop="static" data-target="#model-trash"><i class="ion ion-trash-a"></i></button>
            </div>
        </td>
    </script>
@endpush

resources/views/projects/_partials/deployments.blade.php
<div class="box">
    <div class="box-header">
        <h3 class="box-title">{{ trans('deployments.latest') }}</h3>
    </div>

    @if (!count($deployments))
    <div class="box-body">
        <p>{{ trans('deployments.none') }}</p>
    </div>
    @else
    <div class="box-body table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>{{ trans('app.date') }}</th>
                    <th>{{ trans('deployments.started_by') }}</th>
                    <th>{{ trans('deployments.deployer') }}</th>
                    <th>{{ trans('deployments.committer') }}</th>
                    <th>{{ trans('deployments.commit') }}</th>
                    <th>{{ trans('deployments.branch') }}</th>
                    <th>{{ trans('app.status') }}</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($deployments as $deployment)
                <tr id="deployment_{{ $deployment->id }}">
                    <td>{{ $deployment->id }}</td>
                    <td>{{ $deployment->started_at->format('Y-m-d H:i:s') }}</td>
                    <td>
                        {{ $deployment->is_webhook ? trans('deployments.webhook') : trans('deployments.manually') }}
                        @if (!empty($deployment->reason))
                            <i class="ion ion-ios-chatboxes-outline deploy-reason" data-toggle="tooltip" data-placement="right" title="{{ $deployment->reason }}"></i>
                        @endif
                    </td>
                    <td>
                        @if ($deployment->build_url)
                            <a href="{{ $deployment->build_url }}" target="_blank">{{ $deployment->deployer_name }}</a>
                        @else
                            {{ $deployment->deployer_name }}
                        @endif
                    </td>
                    <td>{{ $deployment->committer_name }}</td>
                    <td>
                        @if ($deployment->commit_url)
                        <a href="{{ $deployment->commit_url }}" target="_blank">{{ $deployment->short_commit_hash }}</a>
                        @else
                        {{ $deployment->short_commit_hash }}
                        @endif
                    </td>
                    <td><a href="{{ $deployment->branch_url }}" target="_blank"><span class="label label-default">{{ $deployment->branch }}</span></a></td>
                    <td>
                        <span class="label label-{{ $deployment->css_class }}"><i class="ion ion-{{ $deployment->icon }}"></i> <span>{{ $deployment->readable_status }}</span></span>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            @if ($deployment->isSuccessful())
                                <button type="button" data-toggle="modal" data-backdrop="static" data-target="#redeploy" data-optional-commands="{{ $deployment->optional_commands_used }}" data-deployment-id="{{ $deployment->id }}" class="btn btn-default btn-rollback @if ($deployment->isCurrent()) hide @endif" title="{{ trans('deployments.rollback') }}"><i class="ion ion-arrow-return-left"></i></button>
                            @endif

                            @if ($deployment->isPending() || $deployment->isRunning())
                                <!-- FIXME: Try and change this to a form as abort should be a POST request -->
                                <a href="{{ route('deployments.abort', ['id' => $deployment->id]) }}" class="btn btn-default btn-cancel" title="{{ trans('deployments.cancel') }}"><i class="ion ion-eye-disabled"></i></a>
                            @endif
                            @if ($deployment->isApproving())
                                <a href="{{ route('deployments.approve', ['id' => $deployment->id]) }}" class="btn btn-default btn-approve" title="{{ trans('deployments.approve') }}"><i class="ion ion-checkmark"></i></a>
                            @endif
                            @if ($deployment->isApproved())
                                <a href="{{ route('deployments.deploy', ['id' => $deployment->id]) }}" class="btn btn-default btn-deploy" title="{{ trans('deployments.deploy') }}"><i class="ion ion-ios-cloud-upload"></i></a>
                            @endif
                            <a href="{{ route('deployments', ['id' => $deployment->id]) }}" type="button" class="btn btn-default" title="{{ trans('app.details') }}"><i class="ion ion-information-circled"></i></a>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {!! $deployments->render() !!}
    </div>

    @endif
</div>

resources/views/projects/_partials/heartbeats.blade.php
<div class="box">
    <div class="box-header">
        <div class="pull-right">
            <button type="button" class="btn btn-success" title="{{ trans('heartbeats.create') }}" data-toggle="modal" data-backdrop="static" data-target="#heartbeat"><span class="ion ion-plus"></span> {{ trans('heartbeats.create') }}</button>
        </div>
        <h3 class="box-title">{{ trans('heartbeats.label') }}</h3>
    </div>

    <div class="box-body" id="no_heartbeats">
        <p>{{ trans('heartbeats.none') }}</p>
    </div>

    <div class="box-body table-responsive" id="heartbeat_list">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th width="10%">{{ trans('heartbeats.name') }}</th>
                    <th width="45%">{{ trans('heartbeats.url') }}</th>
                    <th width="10%">{{ trans('heartbeats.interval') }}</th>
                    <th width="15%">{{ trans('heartbeats.last_check_in') }}</th>
                    <th width="10%">{{ trans('heartbeats.status') }}</th>
                    <th width="10%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

@push('templates')
    <script type="text/template" id="heartbeat-template">
        <td><%- name %></td>
        <td><%- callback_url %></td>
        <td><%- interval_label %></td>
        <td>
            <% if (has_run) { %>
                <%- formatted_date %>
            <% } else { %>
                {{ trans('app.never') }}
            <% } %>
        </td>
        <td>
             <span class="label label-<%- status_css %>"><i class="ion ion-<%-icon_css %>"></i> <%- status %></span>
        </td>
        <td>
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-default btn-edit" title="{{ trans('heartbeats.edit') }}" data-toggle="modal" data-backdrop="static" data-target="#heartbeat"><i class="ion ion-compose"></i></button>
                <button type="button" class="btn btn-danger btn-delete" title="{{ trans('app.delete') }}" data-toggle="modal" data-backdrop="static" data-target="#model-trash"><i class="ion ion-trash-a"></i></button>
            </div>
        </td>
    </script>
@endpush

resources/views/projects/_partials/issues.blade.php
<div class="box">
    <div class="box-header">
        <div class="pull-right">
            <button type="button" class="btn btn-success" title="{{ trans('issues.create') }}" data-toggle="modal" data-backdrop="static" data-target="#issue"><span class="ion ion-plus"></span> {{ trans('issues.create') }}</button>
        </div>
        <h3 class="box-title">{{ trans('issues.label') }}</h3>
    </div>

    <div class="box-body" id="no_issues">
        <p>{{ trans('issues.none') }}</p>
    </div>

    <div class="box-body table-responsive" id="issue_list">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>{{ trans('issues.title') }}</th>
                    <th>{{ trans('issues.content') }}</th>
                    <th>{{ trans('app.created') }}</th>
                    <th>{{ trans('issues.updated_at') }}</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

@push('templates')
    <script type="text/template" id="issue-template">
        <td><%- id %></td>
        <td data-issue-id="<%- id %>"><%- title %></td>
        <td><%- content %></td>
        <td><%- created_at %></td>
        <td><%- updated_at %></td>
        <td>
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-success btn-confirm" title="{{ trans('issues.confirm') }}"><i class="ion ion-ios-checkmark-outline"></i></button>
                <button type="button" class="btn btn-default btn-edit" title="{{ trans('issues.edit') }}" data-toggle="modal" data-backdrop="static" data-target="#issue"><i class="ion ion-compose"></i></button>
                <button type="button" class="btn btn-danger btn-delete" title="{{ trans('issues.delete') }}" data-toggle="modal" data-backdrop="static" data-target="#model-trash"><i class="ion ion-trash-a"></i></button>
            </div>
        </td>
    </script>
@endpush

resources/views/projects/_partials/shared_files.blade.php
<div class="box">
    <div class="box-header">
        <div class="pull-right">
            <button type="button" class="btn btn-success" title="{{ trans('sharedFiles.create') }}" data-toggle="modal" data-target="#sharefile"><span class="ion ion-plus"></span> {{ trans('sharedFiles.create') }}</button>
        </div>
        <h3 class="box-title">{{ trans('sharedFiles.label') }}</h3>
    </div>


    <div class="box-body" id="no_files">
        <p>{{ trans('sharedFiles.none') }}</p>
    </div>

    <div class="box-body table-responsive">
        <table class="table table-striped" id="file_list">
            <thead>
                <tr>
                    <th width="30%">{{ trans('sharedFiles.name') }}</th>
                    <th width="40%">{{ trans('sharedFiles.file') }}</th>
                    <th width="30%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

@push('templates')
    <script type="text/template" id="files-template">
        <td><%- name %></td>
        <td><%- file %></td>
        <td>
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-default btn-edit" title="{{ trans('sharedFiles.edit') }}" data-toggle="modal" data-backdrop="static" data-target="#sharefile"><i class="ion ion-compose"></i></button>
                <button type="button" class="btn btn-danger btn-delete" title="{{ trans('sharedFiles.delete') }}" data-toggle="modal" data-backdrop="static" data-target="#model-trash"><i class="ion ion-trash-a"></i></button>
            </div>
        </td>
    </script>
@endpush